data_dir: ${project_dir}/data
dataset:
  dataset_path: ${data_dir}/Analyze
  eval_set: valid
  nvid: 1
  vids_dict:
    valid:
    - dbdc7605-37d4-4318-a1aa-24627e968602
defaults:
- dataset: soccernet_gs
- eval: gs_hota
- engine: offline
- visualization: gamestate
- modules/bbox_detector: yolo_ultralytics
- modules/bbox_detector_custom: yolo_ultralytics
- modules/reid: prtreid
- modules/track: bpbreid_strong_sort
- modules/jersey_number_detect: mmocr
- modules/team: kmeans_embeddings
- modules/team_side: mean_position
- modules/tracklet_agg: voting_role_jn
- modules/pitch: nbjw_calib
- modules/calibration: nbjw_calib
- modules/player_ball_assigner: player_ball_assigner
- _self_
eval_tracking: false
experiment_name: sn-gamestate
home_dir: ${oc.env:HOME}
hydra:
  job:
    chdir: true
  output_subdir: configs
  run:
    dir: outputs/${job_jd}
  sweep:
    dir: multirun_outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
job_jd: dbdc7605-37d4-4318-a1aa-24627e968602
model_dir: ${project_dir}/pretrained_models
modules:
  bbox_detector:
    batch_size: 8
  calibration:
    batch_size: 1
  jersey_number_detect:
    batch_size: 8
  pitch:
    batch_size: 1
  pose_bottomup:
    batch_size: 8
  reid:
    batch_size: 64
  track:
    batch_size: 64
num_cores: 4
pipeline:
- bbox_detector_custom
- player_ball_assigner
- reid
- track
- pitch
- calibration
- jersey_number_detect
- tracklet_agg
- team
- team_side
print_config: false
project_dir: ${hydra:runtime.cwd}
state:
  load_file: null
  save_file: states/${experiment_name}.pklz
test_tracking: true
use_rich: true
use_wandb: false
visualization:
  cfg:
    save_videos: true
